spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/oauth2?useSSL=false&serverTimezone=UTC
#    username: root
#    password: 111111
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/oauth2?useSSL=false&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 111111

server:
  port: 8080
  servlet:
    jsp:
      init-parameters:
        # jsp修改之后立即生效
        development: true
mybatis:
  mapper-locations: classpath:mappings/**/*.xml
  type-aliases-package: com.github.vspro.persistent.domain
logging:
  level:
    org.springframework: DEBUG









